[rpc_and_lcd_endpoints]
heimdall_rpc_endpoint = "http://localhost:26657"
heimdall_lcd_endpoint = "http://localhost:1317"

[stats_details]
secret_key = "secret_key"
node = "identifier"
net_stats_ip = "localhost:3000"